openapi: 3.0.1
info:
  title: Event Capture
  description: |+
    This microservice is to capture the events.
  version: '0.1.0'
  x-subscribelink: add_event
  x-apitype: Subscription
  x-apitypedescription: |+
    Fast | Single-Call | 10MB/Call
  x-inputfilelimit: |+
    Process up to 10MB of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+

servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - May 08, 2023"
paths:
  /microservices/analytics/eventcapture/v0/addevent:
    description: |+
        This API will be used to capture the events.

    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: 
                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          description: Success Message
          example: "Event capture successfully processed"
        success:
          type: string
          description: Status of the event
          example: "Success"
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid input - Error in URL.
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure 
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - May 08, 2023
                x-details: Initial version release
                description: Latest Version
    input:
      type: object
      required:
        - postcode
      properties:
        user_name:
          type: string
          default: true
          example: Priya
          description: |+ 
            User name
        user_role:
          type: string
          default: true
          example: dc
          description: |+
            Specifiy the user role.
        page_name:
          type: string
          default: true
          example: home
          description: |+
            Specify the page name.
        page_url:
          type: string
          default: true
          example: "https://test.brivge.com/home"
          description: |+
            Specify the page url
        current_page_time:
          type: string
          default: true
          example: 1234
          description: |+
            Specifiy the current page time
        event_id:
          type: integer
          default: true
          example: 1
          description: |+
            Specify the event ID
        event_name:
          type: string
          default: true
          example: Button
          description: |+
            Specify the event name
        previous_event_id:
          type: integer
          default: true
          example: 3
          description: |+
            Specify the previous event ID
        previous_event_name:
          type: string
          default: true
          example: Add Parts
          description: |+
            Specify the previous event name
        previous_page_name:
          type: string
          default: true
          example: Login
          description: |+
            Specify previous page name
        previous_page_url:
          type: string
          default: true
          example: "https://test.brivge.com/Login"
          description: |+
            Specify the previous page url
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
