openapi: 3.0.1
info:
  title: Refresh API Key
  description: This mocroservice is used to refresh user's API Key.
  version: v0.1.0
  x-subscribelink: refresh_api_key
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Jul 09, 2021"
paths:
  /org/v0/refreshapikey:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  user_id: 2196
                  new_api_key: 5D8BA2F849F9...
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            user_id:
              description: User Id of the user
              example: 2196
              type: integer
            new_api_key:
              description: User new api key
              example: "AA6A108150A04..."
              type: string
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Jul 09, 2021
                description: Initial version release  
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
    input:
      type: object
      properties:
        user_id:
          x-name: user_id
          type: integer
          example: 2196
          description: Default it will be based on api key user details. For User Id, Refer to User List API to get the user id (results.user_id) details.
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
