openapi: 3.0.1
info:
  title: User List
  description: This API allows an orgonization admin to access user list inforamtion and data.
  x-subscribelink: user_list
  version: '0.1.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/v0/getuserlist:
    get:
      tags:
        - v1.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                status: Success
                results:
                  - user_id: 2194
                    groups:
                      - id: 2374
                        value: AI & Data (Individual)
                    last_activity: 22 jun 2021 / 12:21
                    user_name: example@example.io
                    created_by: admin
                    date_created: 22 jun 2021 / 20:12
                    root_user: 'yes'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'          
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detail description on the status
        status:
          type: string
          example: Success
          description: The status of the API call Success/Failure
        results:
          type: array
          example: [{<JSON result Object}]
          description: The list of Json result object
          items:
            type: object
            properties: 
                user_id: 
                  type: string
                  description: User id of the user
                  example: "1527"
                groups: 
                  type: object
                  example: {<JSON ressnult Object}
                  properties:                      
                    id:
                      type: integer
                      description: Group Id of the user
                      example: "1491"
                    value:
                      type: string
                      description: Group name of the user
                      example: "AI & Data (Individual)"
                last_activity: 
                  type: string
                  description: Last login activity of the user
                  example: "06 oct 2020 / 11:37"
                user_name: 
                  type: string
                  description: User name of the user
                  example: "example@example.io"
                created_by:
                  type: string
                  description: Created by User name
                  example: "admin"
                date_created: 
                  type: string
                  description: User created date in the format DD MM YY / HH:MM
                  example: "06 oct 2020 / 11:37"
                root_user: 
                  type: string
                  description: |+
                    Root user yes - Super admin of the org
                    Root user no  - User of the org
                  example: "yes"
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
    versions:
      type: object
      properties:
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 09,2021
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
