openapi: 3.0.1
info:
  title: Add Group
  description: This API allows to create a new group in organisation.
  version: v0.1.0
  x-subscribelink: add_group
servers:
  - url: 'https://platform-apis-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Nov 1, 2021"
paths:
  /org/v0/updateorggroup:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '415':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Nov 1, 2021
                description: Initial version release    
    input:
      type: object
      required: 
        - org_group_name
      properties:
        org_group_name:
          x-name: org_group_name
          type: string
          default: True
          example: "Access set group"
          description: Name of new group to the organization
        description:
          x-name: description
          type: string
          example: "testing description"
          description: Group description
        group_functions:
          x-name: group_functions
          type: array
          example: []
          description: List of Function Ids. Refer to Assigned Functions API to get the function id (result.function_id) details.
          items:
            type: object
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
