openapi: 3.0.1
info:
  title: Subscribed Microservices
  description: This API provides operations to manage subscribed microservices in your organization. The organizational subscribed microservices can be adjusted by using the admistrator user dashboard.
  version: v0.1.0
  x-subscribelink: subscribed_microservices
servers:
  - url: 'https://platform-apis-catalog.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - May 12, 2021"
paths:
  /v0/subscribedmicroservices:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                status: success
                message: successfully processed
                results:
                  - microservice: Date Resolution
                    calls: 57
                    spend: 0
                    class: Utility
                    doc_url: 'https://docs.sentient.io/#/utility/date_resolution'
                    endpoint: >-
                      https://dev-apis.sentient.io/microservices/utility/dateresolution/v0/getresults
                  - microservice: Date Resolution
                    calls: 57
                    spend: 0
                    class: Utility
                    doc_url: ''
                    endpoint: >-
                      https://dev-apis.sentient.io/microservices/utility/dateresolution/v0/getresults
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '415':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        status:
          type: string
          example: Success
          description: Activity details
        message:
          type: string
          example: Successfully Processed
          description: Activity details
        results:
          type: array
          example: [{<JSON result Object}]
          description: The list of Json result object
          items:
            type: object
            properties:                      
                microservice:
                  type: string
                  description: Microservice name
                  example: Date Resolution
                calls:
                  type: integer
                  format: float
                  description: Microservice total calls
                  example: 57.0
                spend:
                  type: integer
                  format: float
                  description: Microservice amount spend
                  example: 0.0
                class:
                  type: string
                  description: Microservice class
                  example: Utility
                doc_url:
                  type: string
                  description: Microservice document url
                  example: "https://docs.sentient.io/#/utility/date_resolution"
                endpoint:
                  type: string
                  description: Microservice endpoint
                  example: https://dev-apis.sentient.io/microservices/utility/dateresolution/v0/getresults
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Jun 09, 2021
                description: Initial version release    
    input:
      type: object
      required:
        - from_date
        - to_date
      properties:
        from_date:
          x-name: from_date
          default: True
          type: string
          example: "2021-01-01"
          description: From Date will be in YYYY-MM-DD format.
        to_date:
          x-name: to_date
          default: True
          type: string
          example: "2021-02-24"
          description: To Date will be in YYYY-MM-DD format.
        lang:
          x-name: lang
          type: string
          example: EN
          description: Default lang value is EN. Other supported lang are JA for Japanese.
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
