apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRWDJPczY4d1dBbUp0L2dvY3gyOG9MVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TXpBMU1UVXhNRFF6TURCYUdBOHlNRFV6TURVeE5URXdOVE13TUZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUM3CnQyYm14aW85UENoTVY2d1RCK2cvS3J1RFNJLzk1Q3dkQ0RpQzhXUTJOZm1ZdGlBNFllN3BaOFdrVmFoZkN3SEEKeU9kSEw1Z2ZaM0pNZklpaGRXUDJTY3NyMU9vdVdzeGNwd2ZxYkk2bTFPSWRyNis1Qko2T1N1S0ttb2hOaVVzagpDTnRJem5IREZNNEVwZDNXRExhY0QyWnlGVEdaZnFYMTBpWllnRTh0STZDWXJWc1Q3MHliQS9YZnVxRGt1ZWhmClhod3A5bSsxTWNWZHhTYUd5N3laWWE4Z3Z0RWx0OU9jV3pqZXc5bXZ2dTYrMStEVVRmM2dhT2U4cXhYMkp1VGUKQ3oxcHVVZ0JhRFZFZ2VnQk1PV3NWeWdlcGsxZHZkV1E1bU9pQTRtL1dNaTNzeVhIOUw5amRXUlo0Y3FpbFZRYgpJRkVVQU42ZXdJTWZlLzRBRG9wZlM5YzUxVmtDOU03OWZlWFpuSjFjdWkxQnNsSmZvaXFGU0YzdGpDaEZoelk0CmFmQ0pzK0pCNmY5UkY0ZWw2NC9BTnpCZGN4ZmRUcUxGOEpnRjZoL2VhRVcxZHpGcXlmN1VmSXgrVzhhbzRMdmEKVy9NZzR2SGswNHRlVlUwV3BJeTVQYzRhMDE4MDA1YzBKV0JnK3ZZZWltQTlBS09xTmpEN0pqZ2E2cVREelgyUgozcFJtQkg3RERKMzhVOTVkR3BDelUzdkZ6bkx4SFRxeEZFekVsbFZyOUVTbnBMZWMxOWtqMHp0V0ZlN3NXTWNUCnNEWEx1eldCUzVLR2hRajd5ck1DS1M0OU9abFFEZERsNmFzOXhMVlZCQ0l1bVRmQXlmQ2djVkx1NGVHVTZMNzgKTDU3VGRubnFValhoaUlDRVBlcHQ3NFlmWDFMcHp6bndCMDBkMFpPODR3SURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVjTTVnbUNEY1U2MFdDK3BXCm5JUXpEMW9TanB3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFDcmVKSVZIMWJ0MERSZzlmdjduZk9lSDh3YlkKMm9PMlVhUUF5M0JrS2lBbUVaOTBuWXhLYit2UnRSSkpMY3ExVDFKR3ZvaWIvd0V6VVY4TDU1Sy85NVNqK3g1SwpJT1RyMlNueGVLVEVVcmJ0dUNwVmtRc3hGaXZja3ppclY2TWZxMFFNUDB6YlBjVWEyZW9FSU1lek1UakFDdjlyCkxHTGgwYlJEUUFnQkppbTU4Q0JPbHRiQXNMMHNjcEhtaS9Jc0QxeU82V3pGVmZnSFppd2hLNVZmMHpKYWhmOGsKOXFBM1FIcWszMXpiUjIvZjBpekZoa0I0Y2ZRYWdMb1hHUnJJT0V5MzBwdG1VMUV6OFhYUW9peHBDcDBIeU55dgp6ZTZzMUUvZXRWbFJILzB2UGJIOWZaQVE5M2ZqUFhPcDZSaUZLUGFnRDR4c1ZKS29RQkRIeUZaWjZDSnV1WVY3CnBwY1pHWHZYWUZ5MDdTbW52ZjFORldaNGF1MGR2OWgzTkJXOHo1UllDOFdvMk8zaXh6S05zR25yVWZwNStSMUgKa1l3dVZsNk1NT3NYMDAwOFlqbmdEUVU1Uys2RnJ3UzI1M2ZkQkJEeU9xQ203NXc2SFBnekxCaGk1RkJJQ0V6dApqRXR5N0gxa2kxMXhtMGJqUTRlNVVKaHN5c1RkTHZ2YXlLNGdoTlBXWkhOMGZUZlJvaUkwRXlWTE4zVTFoS1psClN0VXI4Z2xCNjFKSHNQMG1zY3BLQ3ZyaE9xMEk0dzJGVS9JR0lqNS9TNitJSFZpY1JIY2hyWGZjZS9YSXpqQkYKeGROYXJoR28xN0xGcVk2T05kNmgvL0V0L0R2RkI1WkM3K2pPWk82S25pZE4vM0ZiWHVGejNwbmxjbllIWFpsMQpDU0hoNVlicldKWFJoUTZuCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://sentient-prod-ms-dns-37rcp8eb.hcp.southeastasia.azmk8s.io:443
  name: sentient-prod-ms
contexts:
- context:
    cluster: sentient-prod-ms
    user: clusterUser_sentient-prod_sentient-prod-ms
  name: sentient-prod-ms
current-context: sentient-prod-ms
kind: Config
preferences: {}
users:
- name: clusterUser_sentient-prod_sentient-prod-ms
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      - --client-id
      - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
      - --tenant-id
      - de77b20a-46d2-4731-baeb-5345d827b961
      - --login
      - devicecode
      command: kubelogin
      env: null
      installHint: |2

        kubelogin is not installed which is required to connect to AAD enabled cluster.

        To learn more, please go to https://aka.ms/aks/kubelogin
      provideClusterInfo: false
