components:
  schemas:
    create-docinput:
      properties:
        doc_text:
          description: create doc in ES index
          example: How many employes in PropNex.
          type: string
        index_name:
          description: create doc in ES index
          example: llm_chatbot_en
          type: string
      required:
      - doc_text
      - index_name
      type: object
    create-indexinput:
      properties:
        index_name:
          description: Create a new Index in ES
          example: llm_chatbot_en2
          type: string
      required:
      - index_name
      type: object
    delete-indexinput:
      properties:
        index_name:
          description: Delete Index in ES
          example: llm_chatbot_en2
          type: string
      required:
      - index_name
      type: object
    forbidden:
      properties:
        message:
          example: Access Denied Unauthorized User
          type: string
        status:
          example: Failure
          type: string
      type: object
    gatewaytimeout:
      properties:
        message:
          example: Request Timeout
          type: string
        status:
          example: Failure
          type: string
      type: object
    get-messageinput:
      properties:
        index_name:
          description: Get data from ES
          example: llm_chatbot_en
          type: string
        text:
          description: Get data from ES
          example: PropNex won any wards.
          type: string
      required:
      - text
      - index_name
      type: object
    inputfieldmissing:
      properties:
        message:
          example: Input Field Missing
          type: string
        status:
          example: Failure
          type: string
      type: object
    inputlimitexceeded:
      properties:
        message:
          example: Input Limit Exceeded
          type: string
        status:
          example: Failure
          type: string
      type: object
    invalidinput:
      properties:
        message:
          example: Invalid Input
          type: string
        status:
          example: Failure
          type: string
      type: object
    notfound:
      properties:
        message:
          example: Invalid Request URL
          type: string
        status:
          example: Failure
          type: string
      type: object
    paymentrequired:
      properties:
        message:
          example: Insufficient Credits Kindly Top Up
          type: string
        status:
          example: Failure
          type: string
      type: object
    servererror:
      properties:
        message:
          example: Internal Server Error
          type: string
        status:
          example: Failure
          type: string
      type: object
    success:
      properties:
        message:
          description: Description on the API status
          example: Successfully Processed
          type: string
        results: {}
        status:
          description: The status of the API call - success/failure
          example: success
          type: string
      type: object
    unauthorized:
      properties:
        message:
          example: Missing Authentication Token
          type: string
        status:
          example: Failure
          type: string
      type: object
    versions:
      properties:
        v1.0.0:
          items:
            oneOf:
            - description: Current Version
              example: Published Date - Jan 19, 2024
              type: string
              x-details: Initial Version Release
          type: array
      type: object
  securitySchemes:
    APIAuthorizer:
      description: Authentication is done using the x-api-key in the request header
      in: header
      name: x-api-key
      type: apiKey
      x-amazon-apigateway-authtype: custom
info:
  description: 'Only for Demo '
  title: LLM ES Vector Indexing Demo
  version: v1.0.0
  x-billingmethod: The API is billed by the amount of data transferred.
  x-inputfilelimit: Process up to 1 GB of File Size.
  x-responsetime: The response rate is slower than the small file API due to large data.
openapi: 3.0.1
paths:
  /microservice/custommodels/tsregistermsllmesvectorindexingdemo/v1/create-doc:
    description: create doc in ES index
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-docinput'
        required: true
      responses: &id001
        '200':
          content:
            application/json:
              example: '{}'
              schema:
                $ref: '#/components/schemas/success'
          description: ok
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
          description: Unauthorized
        '402':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
          description: Payment Required
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
          description: Not Found
        '413':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
          description: Payload Too Large
        '415':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
          description: Unsupported Media Type
        '419':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
          description: Input Field Missing
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
          description: Internal Server Error
        '504':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
          description: Gateway Timeout
      security: &id002
      - APIAuthorizer: []
      tags: &id003
      - v1.0.0
  /microservice/custommodels/tsregistermsllmesvectorindexingdemo/v1/create-index:
    description: Create a new Index in ES
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-indexinput'
        required: true
      responses: *id001
      security: *id002
      tags: *id003
  /microservice/custommodels/tsregistermsllmesvectorindexingdemo/v1/delete-index:
    description: Delete Index in ES
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delete-indexinput'
        required: true
      responses: *id001
      security: *id002
      tags: *id003
  /microservice/custommodels/tsregistermsllmesvectorindexingdemo/v1/get-message:
    description: Get data from ES
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/get-messageinput'
        required: true
      responses: *id001
      security: *id002
      tags: *id003
servers:
- url: https://apisa.sentient.io
tags:
- description: Published Date - Jan 19, 2024
  name: v1.0.0
