components:
  schemas:
    addinput:
      properties:
        a:
          description: adding two values
          example: 10
          type: number
        b:
          description: adding two values
          example: 20
          type: number
      required:
      - a
      - b
      type: object
    divinput:
      properties:
        a:
          description: twenty
          example: 20
          type: number
        b:
          description: two
          example: 2
          type: number
      required:
      - a
      - b
      type: object
    forbidden:
      properties:
        message:
          example: Access Denied Unauthorized User
          type: string
        status:
          example: Failure
          type: string
      type: object
    gatewaytimeout:
      properties:
        message:
          example: Request Timeout
          type: string
        status:
          example: Failure
          type: string
      type: object
    inputfieldmissing:
      properties:
        message:
          example: Input Field Missing
          type: string
        status:
          example: Failure
          type: string
      type: object
    inputlimitexceeded:
      properties:
        message:
          example: Input Limit Exceeded
          type: string
        status:
          example: Failure
          type: string
      type: object
    invalidinput:
      properties:
        message:
          example: Invalid Input
          type: string
        status:
          example: Failure
          type: string
      type: object
    mulinput:
      properties:
        a:
          description: ten
          example: 10
          type: number
        b:
          description: five
          example: 5
          type: number
      required:
      - a
      - b
      type: object
    notfound:
      properties:
        message:
          example: Invalid Request URL
          type: string
        status:
          example: Failure
          type: string
      type: object
    paymentrequired:
      properties:
        message:
          example: Insufficient Credits Kindly Top Up
          type: string
        status:
          example: Failure
          type: string
      type: object
    servererror:
      properties:
        message:
          example: Internal Server Error
          type: string
        status:
          example: Failure
          type: string
      type: object
    subinput:
      properties:
        a:
          description: subtract the two values
          example: 15
          type: number
        b:
          description: subtract the two values
          example: 5
          type: number
      required:
      - a
      - b
      type: object
    success:
      properties:
        message:
          description: Description on the API status
          example: Successfully Processed
          type: string
        results: {}
        status:
          description: The status of the API call - success/failure
          example: success
          type: string
      type: object
    unauthorized:
      properties:
        message:
          example: Missing Authentication Token
          type: string
        status:
          example: Failure
          type: string
      type: object
    versions:
      properties:
        v1.0.0:
          items:
            oneOf:
            - description: Archived
              example: Published Date - Nov 02, 2023
              type: string
              x-details: Initial Version Release
          type: array
        v1.1.0:
          items:
            oneOf:
            - description: Current Version
              example: Published Date - Nov 02, 2023
              type: string
              x-details: div and mul added
          type: array
      type: object
  securitySchemes:
    APIAuthorizer:
      description: Authentication is done using the x-api-key in the request header
      in: header
      name: x-api-key
      type: apiKey
      x-amazon-apigateway-authtype: custom
info:
  description: this is newrepotesting description
  title: newrepotesting
  version: v1.1.0
  x-billingmethod: The API is billed by per request.
  x-inputfilelimit: Process Single Json per api call
  x-responsetime: Response rate is fast due to small data transfer per call mad
openapi: 3.0.1
paths:
  /microservice/custommodels/tsregistermsnewrepotesting/v1/getdiv:
    description: division of two values
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/divinput'
        required: true
  /microservice/custommodels/tsregistermsnewrepotesting/v1/getmul:
    description: multiply of two values
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mulinput'
        required: true
servers:
- url: https://apisa.sentient.io
tags:
- description: Published Date - Nov 02, 2023
  name: v1.1.0
