openapi: 3.0.1
info:
  title: Named-Entity Recognition ENG
  description: |+
      This NLP microservice locates and classifies the named-entity classes from input unstructured English text and also returns the entity start and end positions.</br>
      The named-entity classes extracted include people's names, nationalities, religious groups, political groups, buildings and facilities, organisations, geopolitical, locations, products, events, works of art, laws, languages, dates and time, percentages, monetary values, quantities, ordinals and cardinals.</br>
      This microservice automatically extracts structured information from unstructured text data such as chat logs, emails, news articles, etc.</br>
      The input text **should not exceed 5000 characters**.
  version: '2.0.0'
  x-additionalinfo: |+
    Suggested Use Cases:
    - Extracting structured pre-defined information from text.</br>
    - Gain insights from online customers - extract structured information from unstructured text data such as chat logs, emails, news articles, etc. to find and label fields within a document and then apply sentiment analysis to understand customer opinions to find actionable product and UX insights.</br>
    - Entity analysis - identify entities within documents, including receipts, invoices, and contracts; and label them by types such as date, person, contact information, organization, location, events, products, and media.</br>
  x-subscribelink: named-entity_recognition_eng
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 5000 characters/Call
  x-inputfilelimit: |+
    Process up to 5000 characters per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Limit cannot exceed 5000 characters.
  x-apidetailsdesc: |+
    Locates and Classifies named-entities classes from unstructured English text.
servers:
  - url: 'https://apish.sentient.io'
tags:
- name: "v2.0.0"
  description: "Published Date - Feb 28, 2022"
paths:
  /microservices/nlp/namedentityrecognition/v2/getpredictions:
    post:
      tags:
        - v2.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: {"message": "Successfully Processed","results": {"cardinal": [{"entity": "77","start": 45,"end": 47},{"entity": "11.59pm","start": 520,"end": 527},{"entity": "14","start": 569,"end": 571}],"status": "Success"}}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'  
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties: 
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json object in returned results
          properties:
            person:
              x-name: person
              type: array
              example: [{"end": 3,"entity": "Donald Trump","start": 1}]
              description: Name of persons, including fictional
            other:
              x-name: other
              type: array
              example: [{"entity":"Chinese","start": 1,"end": 2},{"entity":Singaporean,"start": 4,"end": 5},{"entity": Malay,"start": 6,"end": 7}]
              description: Other miscellaneous classes
            facility:
              x-name: facility
              type: array
              example: [{"entity":Changi Airport,"start": 1,"end": 3}]
              description: Buildings, airports, highways, bridges, etc.
            organization:
              x-name: organization
              type: array
              example: [{"entity": "ICAO","start": 14,"end": 15}]
              description: Companies, agencies, institutions, etc.
            geopolitical:
              x-name: geopolitical
              type: array
              example: [{"entity": "Singapore","start": 0,"end": 1}]
              description: Countries, cities, states.
            location:
              x-name: location
              type: array
              example: [{"entity":"Asia","start": 42,"end": 43}]
              description: Non-GPE locations, mountain ranges, bodies of water
            product:
              x-name: product
              type: array
              example: [{"entity": Formula 1,"start": 5,"end": 7}]
              description: Objects, vehicles, foods, etc. (Not services.)
            event:
              x-name: event
              type: array
              example: [{"entity": the Second World War,"start": 1,"end": 5}]
              description: Named hurricanes, battles, wars, sports events, etc.
            work_of_art:
              x-name: work_of_art
              type: array
              example: [{"entity":Wizardry,"start": 1,"end": 2}]
              description: Titles of books, songs, etc.
            law:
              x-name: law
              type: array
              example: [{"entity":the Penal Code,"start": 1,"end": 4}]
              description: Named documents made into laws
            language:
              x-name: language
              type: array
              example: [{"entity": English,"start": 1,"end": 2}]
              description: Any named language.
            date:
              x-name: date
              type: array
              example: [{"entity": Tuesday,"start": 1,"end": 2}]
              description: Absolute or relative dates or periods
            time:
              x-name: time
              type: array
              example: [{"entity": twenty-four hours,"start": 1,"end": 5}]
              description: Times smaller than a day
            percent:
              x-name: percent
              type: array
              example: [{"entity": 91%,"start": 1,"end": 2},{"entity": 25%,"start": 2,"end": 3},{"entity": 61%,"start": 4,"end": 5}]
              description: Percentage, including ”%“
            money:
              x-name: money
              type: array
              example: [{"entity": up to $1000,"start": 1,"end": 4}]
              description: Monetary values, including unit
            quantity:
              x-name: quantity
              type: array
              example: [{"entity": about one degree,85 miles,137 kilometres,"start": 1,"end": 8}]
              description: Measurement units, as of weight or distance
            ordinal:
              x-name: ordinal
              type: array
              example: [{"entity": ninth,"start": 1,"end": 2},{"entity": seventh,"start": 3,"end": 4},{"entity": second,"start": 5,"end": 6}]
              description: Ordinal numbers found in the text string, e.g “first”, “second”, etc
            cardinal:
              x-name: cardinal
              type: array
              example: [{"entity": four,"start": 1,"end": 2}]
              description: Numerals that do not fall under another type. 
        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure  
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v3.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25, 2022
              x-details: New model 
              description: New Model Update
        v2.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Feb 28, 2022
              x-details: Merged Spacy ner and change in Output format
              description: End-of-life by May 31,2023 
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Sep 30, 2020
              x-details: Updated version release v1.0
              description: Archived 
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25, 2019
              x-details: Initial version release 
              description: Archived
    input:
      type: object
      required:
        - text
      properties:
        text:
          x-name: text
          type: string
          default: true
          example: SINGAPORE - Immigration officers have issued 77 stay-home notices as of noon on Wednesday (Feb 19), 12 hours after the scheme kicked in.These notices were issued to Singapore residents, long-term pass holders and foreign workers who have travelled to mainland China in the last 14 days, said the Immigration and Checkpoints Authority (ICA) in response to queries on Thursday.Travellers from Hubei province are excluded from this scheme, as they are quarantined.Those who are issued the new notices, which took effect at 11.59pm on Tuesday, cannot leave their homes for 14 days./n This is stricter than the leave of absence (LOA), which allowed people to briefly leave their homes for necessities. LOA will no longer be issued.Those who do not observe the stay-home period can be prosecuted under the Infectious Diseases Act, warned the ICA.They could be fined up to $10,000 or jailed for up to six month, or both, for the first offence. For subsequent offences, this could go up to a maximum of $20,000 and up to a year.
          description: |+
            Input text.
            
            Supported formats: ASCII only
        return_entity_position:
          x-name: return_entity_position
          type: boolean
          default: false
          example: true
          description: |+
            Boolean value indicating whether entity position needs to be returned or not. Default value is True.
        legacy_output:
          x-name: legacy_output
          type: boolean
          default: false
          example: false
          description: |+
            Boolean value indicating whether the output should be of legacy output format. Default value is False.    
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
