
openapi: 3.0.1
info:
  title: Sentence Paraphrase
  description: |+
    This NLP microservice takes in English sentences in informal / colloquial tone and rewrites it in a formal tone. It helps to smooth out sentences that contains irregularities (profanities, grammatical errors, awkward sentence structures) that can be typically found in informal dialogues or conversations.
    
    The input text sentence should have less than 60 sub-words. Any excess words in the sentence beyond that limit will be ignored. As a word may often consist of 2 or more sub-words (e.g. “thumbnail” consists of the sub-words “thumb” and “nail”), generally, we suggest keeping the input sentence to around 30 to 50 words to be safe.
  version: v0.1.0
  x-subscribelink: sentence_paraphrase
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 50 words/Call
  x-inputfilelimit: |+
    Process up to 50 words per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Limit cannot exceed 50 words.
  x-apidetailsdesc: |+
    English sentences in informal / colloquial tone and rewrites it in a formal tone.  
servers:
  - url: 'https://apis.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Feb 24, 2022"
paths:
  /microservices/nlp/paraphrase/v0/getpredictions:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results: 
                  output: They have to keep increasing the water prices if we don't save.

                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'       
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          description: The result of the API call
          example: { "<Json": "Object>" }
          properties: 
            output:
              description: Paraphrased output text
              example: They have to keep increasing the water prices if we don't save.
              type: string

        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure
        
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Feb 24, 2022
                x-details: Initial version release
                description: Initial Release    
    input:
      type: object
      required:
      
        - text
      
      properties:
        text:
          x-name: text
          type: string
          default: True
          example: if we don't save, they have to keep on increasing the water prices, and we have to play more.
          description: |+
            Input text.
        
        
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
