openapi: 3.0.1
info:
  title: spaCy NER
  description: |+
  
      This NLP microservice locates and classifies the named-entity classes from input unstructured English text, based on the spaCy model. The named-entity classes extracted include people's names, nationalities, religious groups, political groups, buildings and facilities, organisations, geopolitical, locations, products, events, works of art, laws, languages, dates and time, percentages, monetary values, quantities, ordinals and cardinals.
      It can also return the start and end positions of the identified entities in the text by setting the optional parameter "entity_position". This microservice automatically extracts structured information from unstructured text data such as chat logs, emails, news articles, etc.

      The input text **should not exceed 5000 characters**.
  
  x-additionalinfo: |+
    Suggested Use Cases:
    - Can be used to build information extraction or natural language understanding systems, or to pre-process text for deep learning -e.g. tokenization, Parts-of-Speech (PoS) Tagging, Text Classification and Named Entity Recognition.
  version: '1.0.0'
  x-subscribelink: spacy_ner
  x-apitype: small file
  x-apitypedescription: |+ 
    Fast | Single-Call | 5000 characters/Call
  x-inputfilelimit: |+
    Process up to 5000 characters per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Limit cannot exceed 5000 characters.
  x-apidetailsdesc: |+
    Locates and Classifies the named-entities classes from input unstructured English text.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v1.0.0"
  description: "Depreciation Date - May 31, 2022"
paths:
  /microservices/nlp/spacyner/v1/getpredictions:
    post:
      tags:
        - v1.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: {"message": "Successfully Processed","results": {"fac": [["Changi Airport",1,3],["Changi Airport",7,9],["the first Airport",71,74]],"gpe": [["Singapore",0,1],["Singapore",3,32],["Changi",109,110],["Singapore",116,117],["Singapore",129,130],["Singapore",162,163]],"loc": [["Asia",42,43],["Marina Bay",126,128]],"org": [["ICAO",14,15],["WSSS",16,17],["FAA",18,19],["the World's Best Airport",63,68],["Skytrax",69,70],["Changi Airport Group",152,155],["Jetstar Asia Airways",173,176],["BOC Aviation",177,179]],"quantity": [["approximately 20 km",118,121],["5.0 sq mi",141,144]]},"status": "Success"}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'  
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties: 
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json object in the returned results
          properties:
            person:
              x-name: person
              type: string
              example: [[Donald Trump,1,3]]
              description: People, including fictional.
            norp:
              x-name: norp
              type: string
              example: [[Chinese,1,2],[Singaporean,4,5],[Malay,6,7]]
              description: Nationalities or religious or political groups.
            fac:
              x-name: fac
              type: string
              example: [[Changi Airport,1,3], ["Changi Airport",7, 9],["the first Airport",71,74]]
              description: Buildings, airports, highways, bridges, etc.
            org:
              x-name: org
              type: string
              example: [["ICAO",14,15],["WSSS",16,17],["FAA",18,19],["the World's Best Airport",63,68],["Skytrax",69,70],["Changi Airport Group",152,155],["Jetstar Asia Airways",173,176],["BOC Aviation",177,179]]
              description: Companies, agencies, institutions, etc.
            gpe:
              x-name: gpe
              type: string
              example: [["Singapore",0,1],["Singapore",31,32],["Changi",109,110],["Singapore",116,117],["Singapore",129,130],["Singapore",162,163]]
              description: Countries, cities, states.
            loc:
              x-name: loc
              type: string
              example: [["Asia",42,43],["Marina Bay",126,128]]
              description: Non-GPE locations, mountain ranges, bodies of water.
            product:
              x-name: product
              type: string
              example: [[Formula 1, 5,7],[Motorrad,8,9]]
              description: Objects, vehicles, foods, etc. (Not services.)
            event:
              x-name: event
              type: string
              example: [[the Second World War,1,5]]
              description: Named hurricanes, battles, wars, sports events, etc.
            work_of_art:
              x-name: work_of_art
              type: string
              example: [[Wizardry,1,2]]
              description: Titles of books, songs, etc.
            law:
              x-name: law
              type: string
              example: [[the Penal Code,1,4],[the Internal Security Act,5,9],[the Constitution of the Republic of Singapore,9,16],[the Evidence Act,16,19],[the Societies Act,19,22]]
              description: Named documents made into laws.
            language:
              x-name: language
              type: string
              example: [[English,1,2]]
              description: Any named language.
            date:
              x-name: date
              type: string
              example: [[Tuesday,1,2]]
              description: Absolute or relative dates or periods.
            time:
              x-name: time
              type: string
              example: [[twenty-four hours,1,5]]
              description: Times smaller than a day.
            percent:
              x-name: percent
              type: string
              example: [[91%,1,2],[25%,2,3],[61%,4,5]]
              description: Percentage, including ”%“.
            money:
              x-name: money
              type: string
              example: [[up to $1000,1,4]]
              description: Monetary values, including unit.
            quantity:
              x-name: quantity
              type: string
              example: [[about one degree,85 miles,137 kilometres,1,8]]
              description: Measurements, as of weight or distance.
            ordinal:
              x-name: ordinal
              type: string
              example: [[ninth,1,2],[seventh,3,4],[second,5,6]]
              description: “first”, “second”, etc.
            cardinal:
              x-name: cardinal
              type: string
              example: [[four,1,2]]
              description: Numerals that do not fall under another type.
        message:
          x-name: message
          type: string
          example: Successfully Processed
          description: Description of the API status.
          
        status:
          x-name: status
          type: string
          example: Success
          description: The status of the API call - success/failure.
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure      
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure  
    input:
      type: object
      required:
        - text
      properties:
        text:
          x-name: text
          type: string
          default: true
          example: "Singapore Changi Airport, commonly known as Changi Airport (IATA: SIN, ICAO: WSSS, FAA LID: SIN), is a major civilian airport that serves Singapore, and is one of the largest transportation hubs in Asia. As one of the world's busiest airports by international passenger and cargo traffic, it is currently rated the World's Best Airport by Skytrax, the first Airport in the world to do so for eight consecutive years.[10][11] It has also been rated as the one of the world's cleanest airports and highly rated international transit airports.[12][13]The airport is located in Changi, at the eastern end of Singapore, approximately 20 km (12 mi)[14] from Marina Bay (Singapore's Downtown Core), on a 13-square-kilometre (5.0 sq mi) site. The airport is operated by Changi Airport Group and it is the home base of Singapore Airlines,[15] Singapore Airlines Cargo,[15] SilkAir,[15] Scoot, Jetstar Asia Airways and BOC Aviation."
          description: |+
            Input text
        return_entity_position:
          x-name: return_entity_position
          type: boolean
          default: false
          example: false
          description: |+
            Boolean value indicating whether entity position needs to be returned or not. Default value is False.
    versions:
      type: object
      properties: 
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 26, 2021
              x-details: Optional input parameter introduced. Output Format Changed  
              description: End-of-life by May 31,2022
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Sep 30, 2020
              x-details: Initial version release    
              description: Depreciated on Jul 07, 2022      
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
