openapi: 3.0.1
info:
  title: Automatic Speech Recognition CHI (Large File)
  description: |+
    This Voice microservice takes in the input audio file  and supports recognizing a speech.The server returns the recognition result in a JSON format as a response. 
    For longer audio, we suggest breaking them up into smaller chunks and making multiple calls to this microservice for more effective transcription.
    - Supports the following audio coding formats: pulse-code modulation (PCM) (uncompressed PCM or WAV files), Opus, and 16-bit mono.
    - Supports the following audio sampling rates: 8,000 Hz and 16,000 Hz.
    - Allows you to specify whether to add punctuation marks during post-processing, and whether to convert Chinese numerals to Arabic numerals.    
  x-additionalinfo: |+
    Kindly note that large file / asynchronous processing requires multiple steps and calling multiple API end-points sequentially to complete the entire processing. The guide below provides detailed steps to try out processing a large file without any coding. You may also need the file upload form https://sentient.io/upload/form.html
  x-tutorial-pdf-doc: 
      https://storage.googleapis.com/lpdocs/docs/alibaba_chinese_asr.pdf   
  version: '0.1.0'
  x-subscribelink: automatic_speech_recognition_chi
  x-apitype: large file
  x-apitypedescription: |+
    Asyncronous | Batch | 1GB/File.
  x-inputfilelimit: |+
    Process up to 1 GB of File Size.
  x-responsetime: |+
    The response rate is slower than the small file API due to large data.
  x-billingmethod: |+
    The API is billed by the amount of data transferred.
  x-notes: |+
    Size cannot exceed 1 GB.
  x-apidetailsdesc: |+
    Supports recognizing short speech and returns the recognition for Larger Files.
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - Dec 30, 2021"
paths:
  /async/microservices/voice/alibabachiasr/v0/getuploadurl:
    description: |+
      Get the pre-signed url to upload the file.
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  fields:
                    content-type: audio/wav
                    key: >-
                      309/495/lp-alibabachiasr/input/chinetest_4f079ca05c614d789252db1d574664d8.wav
                    policy: >-
                      eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJhdWRpby93YXYiXSxbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwwLDQ2Mzc1Ml0seyJjb250ZW50LXR5cGUiOiJhdWRpby93YXYifSx7IngtZ29vZy1tZXRhLWFkZGl0aW9uYWxfcGFyYW0iOiJOb25lIn0seyJ4LWdvb2ctbWV0YS1vaWQiOiIzMDkifSx7IngtZ29vZy1tZXRhLXVpZCI6IjQ5NSJ9LHsieC1nb29nLW1ldGEtdXBsb2FkZXIiOiJmMzYzN2UwN2JjM2I0NWNkYmM3NDY4NjM5NWRmNDNmYSJ9LHsieC1nb29nLW1ldGEtdXVpZCI6IjRmMDc5Y2EwNWM2MTRkNzg5MjUyZGIxZDU3NDY2NGQ4In0seyJidWNrZXQiOiJ1c2VyX3NwYWNlX2RldiJ9LHsia2V5IjoiMzA5LzQ5NS9scC1hbGliYWJhY2hpYXNyL2lucHV0L2NoaW5ldGVzdF80ZjA3OWNhMDVjNjE0ZDc4OTI1MmRiMWQ1NzQ2NjRkOC53YXYifSx7IngtZ29vZy1kYXRlIjoiMjAyMTEyMjBUMDQyOTQwWiJ9LHsieC1nb29nLWNyZWRlbnRpYWwiOiJzZW50aWVudC1kZXYtYmlncXVlcnlAc2VudGllbnQtMjA3MzEwLmlhbS5nc2VydmljZWFjY291bnQuY29tLzIwMjExMjIwL2F1dG8vc3RvcmFnZS9nb29nNF9yZXF1ZXN0In0seyJ4LWdvb2ctYWxnb3JpdGhtIjoiR09PRzQtUlNBLVNIQTI1NiJ9XSwiZXhwaXJhdGlvbiI6IjIwMjEtMTItMjBUMDU6Mjk6NDAuNDM3NTk2WiJ9
                    x-goog-algorithm: GOOG4-RSA-SHA256
                    x-goog-credential: >-
                      sentient-dev-bigquery@sentient-207310.iam.gserviceaccount.com/20211220/auto/storage/goog4_request
                    x-goog-date: 20211220T042940Z
                    x-goog-meta-additional_param: None
                    x-goog-meta-oid: '309'
                    x-goog-meta-uid: '495'
                    x-goog-meta-uploader: f3637e07bc3b45cdbc74686395df43fa
                    x-goog-meta-uuid: 4f079ca05c614d789252db1d574664d8
                    x-goog-signature: >-
                      304d7e52afcea3d6e41818b7c3c71973f275ff979c1280c174b902498eb7bf8f8083dde132af0751ea1fd03a6b3f5e01a6427f5ac05c143da7e9fca53a5c7603b98330291ddb7d90a441eb5ec51340b96a3142497f42dbe6771fabdcfee7dfdc5fd7c0f0fc23dbdfab263fabd1de9a832ee37ec34d4a20e9af6152b708e147d7ae2d02c7f77a2c58577ae2e64914a664d7af6ff0799390c7641e1865affb5749ad40711c9d4049a6a87efe7125257790767c6de237cddd76a1f4bc7662c324b02d770b62f01b7b79b1ea6e8dae0e15f7661c126d8312ba04bcc8c7d290acc7cabf7670d48c4f68272036ba7c545ad04771605db41acabb2bb6e850e9c9d094bf
                  jid: e7fe34e9c21c4d75bc94051e476141c5
                  request_cost: 0.0319
                  url: 'https://storage.googleapis.com/user_space_dev/'
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
  /upload:
    description: |+
      Upload your file to start processing.
    post:
      servers:
        - url: 'https://storage.googleapis.com/user_space_dev/'
          description: Override base path for the GET /ping operation    
      tags:
        - v0.1.0
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadinput'
        required: true          
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: 
                message: Successfully Processed         
  /async/microservices/voice/alibabachiasr/v0/getstatus:
    description: |+
      Query for processing status.
    get:
      tags:
        - v0.1.0
      parameters:
        - in: query
          name: jid
          schema:
            type: string
          example: 36d075917dcd481e9daf858a2549f3b1
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getsuccess'
              example: 
                last_updated: '2021-07-06 12:50:30'
                message: File Processing Successfully Started
                request_cost: 0.086
                status: Processing

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    getsuccess:
      type: object
      properties:
        last_updated:
          type: string
          example: 2021-07-06 12:50:30
          description: Last updated
        message:
          type: string
          example: File Processing Successfully Started
          description: Detail description on the API status
        request_cost:
          type: string
          example: 0.086
          description: Detail description on the API status
        status:
          type: string
          example: Processing
          description: Detail description on the API status
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json Object of returned results
          properties:   
            fields:
              type: object
              example: { "<Json": "Object>" }
              description: Json Object of returned results
              properties:
                content-type:
                  type: string
                  example: text/plain
                  description: Content type of the document
                policy:
                  type: string
                  example: eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ...
                  description: Content type of the document
                x-goog-algorithm:
                  type: string
                  example: GOOG4-RSA-SHA256
                  description: Google algorithm
                x-goog-credential:
                  type: string
                  example: sentient-dev-bigqu...
                  description: Google algorithm
                x-goog-date:
                  type: string
                  example: 20211123T105846Z
                  description: Google algorithm
                x-goog-meta-additional_param:
                  type: string
                  example: None
                  description: Google algorithm
                x-goog-meta-oid:
                  type: string
                  example: 1
                  description: Google algorithm
                x-goog-meta-uid:
                  type: string
                  example: 2
                  description: Google algorithm
                x-goog-meta-uuid:
                  type: string
                  example: 1991d4936ddb4728afaa06cb260b0253
                  description: Google algorithm
                x-goog-signature:
                  type: string
                  example: 3d882f0762743e39146aae926435bf0b15e844836dbcf...
                  description: Google algorithm
            jid:
              type: string
              example: 1991d4936ddb4728afaa06cb260b0253...
              description: Google algorithm 
            request_cost:
              type: string
              example: 0
              description: Google algorithm 
            url:
              type: string
              example: https://storage.googleapis.com/user_space_dev/
              description: Google algorithm 
        status:
          type: string
          example: Success
          description: The status of the API call success/failure                  
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid input - Error in URL.
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure 
    versions:
      type: object
      properties: 
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Dec 30, 2021
              x-details: Initial version release  
              description: Latest Version
    input:
      type: object
      required:
        - file_name
      properties:
        file_name:
          x-name: file_name
          type: string
          default: true
          format: binary
          example: '4 test.wav'
          description: |+
            Name of file to be upload.
        file_size:
          x-name: file_size
          type: integer
          default: true
          example: 4746636
          description: |+
            Size of the file. Maximum size should be 1 GB.
        content_type:
          x-name: content_type
          type: string
          default: true
          example: 'audio/wav'
          description: |+
            Specify the content-type. Pick any one from below list based on input file type.
            ["audio/wav","audio/aac","audio/midi","audio/x-midi","audio/mpeg","audio/opus", "audio/webm","audio/3gpp","audio/3gpp2"]
    uploadinput:
      type: object
      required:
        - filePath      
      properties:
        fields:
          type: object
          example:
            <Json: Object>
          description: Json Object of returned results
        content-type:
          type: string
          example: text/plain
          description: Content type of the document
        policy:
          type: string
          example: eyJjb25kaXRpb25zIjpbWyJlcSIsIiRDb250ZW5...
          description: Content type of the document
        x-goog-algorithm:
          type: string
          example: GOOG4-RSA-SHA256
          description: Google algorithm
        x-goog-credential:
          type: string
          example: sentient-dev-bigqu...
          description: Google algorithm
        x-goog-date:
          type: string
          example: 20211220T042940Z
          description: Google algorithm
        x-goog-meta-additional_param:
          type: string
          example: None
          description: Google algorithm
        x-goog-meta-oid:
          type: string
          example: 309
          description: Google algorithm
        x-goog-meta-uid:
          type: string
          example: 495
          description: Google algorithm
        x-goog-meta-uploader:
          type: string
          example: f3637e07bc3b45cdbc74686395df43fa
          description: Google algorithm
        x-goog-meta-uuid:
          type: string
          example: 4f079ca05c614d789252db1d574664d8
          description: Google algorithm
        x-goog-signature:
          type: string
          example: 304d7e52afcea3d6e41818b7c3c71973f275...
          description: Google algorithm
        jid:
          type: string
          example: e7fe34e9c21c4d75bc94051e476141c5
          description: Google algorithm
        request_cost:
          type: string
          example: 0.0298
          description: Google algorithm
        url:
          type: string
          example: 'https://storage.googleapis.com/user_space_dev/'
          description: Google algorithm
    status:
      type: string
      example: Success
      description: The status of the API call success/failure           
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
