openapi: 3.0.1
info:
  title: Online Command Automatic Speech Recognition ENG
  version: '0.1.0'
  x-apitypedescription: |+
    Fast | Single-Call | 60 mins/socket
  x-inputfilelimit: |+
    Process up to 60 mins/socket of audio file.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per every mins.
  x-notes: |+
    Limit cannot exceed 60 mins audio.
  x-apidetailsdesc: |+
    Recognize text from streaming audio file upto 60 mins and audio file should be in WAV and 16000 kz.
servers:
  - url: 'wss://onlinecommandasr.sentient.io'
# tags must include in to the documentation, to read the description text for published date
tags:
- name: "v0.1.0"
  description: "Published Date - Aug 31, 2020"
html: |+
     <iframe src="https://docs.sentient.io/static/online_command_automatic_speech_recognition_eng_sg.html" width="100%" height="800px">
     </iframe>
paths:
  /:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
components:
  schemas:
    versions:
      type: object
      properties:
        v0.1.0:
          type: array
          items:
            oneOf:
            - type: string
              example: Published Date - Aug 31, 2020
              x-details: Initial version release
              description: Latest Version
