openapi: 3.0.1
info:
  title: Newspaper Article Scraper
  description: |+
    This Utility microservice extracts  and curates articles and delivers Instapaper-style article extraction. </br>
    Current supported languages: Arabic, Russian, Dutch, German, English, Spanish, French, Hebrew, Italian, Korean, Norwegian, Persian, Polish, Portuguese, Swedish, Hungarian, Finnish, Danish, Chinese, Indonesian, Vietnamese, Swahili, Turkish, Greek, Ukrainian. Supports automatic language detection.</br>
    Note that the URL has to be **spelt in full**, including "https://www."
  x-additionalinfo: |+
    Suggested Use Cases:
    - Can be used in services related to the creation of a real-time web application that gathers data from several newspapers and shows a summary of the different topics that are being discussed in the news articles.
  version: '0.1.0'
  x-subscribelink: newspaper_article_scraper
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | One News URL /Call
  x-inputfilelimit: |+
    Process One News URL per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Allows One news URL per request.
  x-apidetailsdesc: |+
    Extracts  and Curates articles from news URL.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - Aug 07, 2020"
paths:
  /microservices/utility/newsarticle/v0.1/getresults:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                content:
                  all_images:
                  - https://static.bangkokpost.com/media/content/20170620/2363063.jpg
                  - https://www.bangkokpost.com/media/content/20170620/c1_1272315_170620160518_620x413.jpg
                  - https://static.bangkokpost.com/media/content/20170620/2364459.jpg
                  - https://static.bangkokpost.com/media/content/20170620/2363071.jpg
                  - https://static.bangkokpost.com/media/content/20170620/2364455.jpg
                  - https://static.bangkokpost.com/media/content/20170620/2363075.jpg
                  authors:
                  - Bangkok Post Public Company Limited
                  keywords:
                  - scholarships
                  - opportunities
                  - fair
                  - study
                  - learning
                  - worlds
                  language: en
                  link: https://www.bangkokpost.com/learning/news/1272315/study-and-work-in-australia-%E2%80%93-many-opportunities-ahead-
                  publish_date: 2020-09-30T07:11:15
                  summary: |-
                    Australia is a country welcoming international students to study at all levels of education with its quality and the part-time work rights given.
                    Moreover, there are opportunities to work full-time and to migrate and hold Australian citizenship after graduation from Australia.
                    Study, Work and Live in one of the World's most liveable countries.
                    "Post Study Work Rights and Pathways to Australian Permanent
                  text: |-
                    Australia is a country welcoming international students to study at all levels of education with its quality and the part-time work rights given. Moreover, there are opportunities to work full-time and to migrate and hold Australian citizenship after graduation from Australia. Especially, engineers, IT specialists and accountants, and many more, are on the list of occupations which Australia is demanding.
                
                    Study, Work and Live in one of the World's most liveable countries.
                
                    Don't miss the chance to interview directly with 40 leading universities and institutions from across Australia. Application fee waivers and scholarships are also available.
                
                    Unique! "Post Study Work Rights and Pathways to Australian Permanent Resident" seminar by Dr. Visa, Australian Registered Migration Agent, and special talks by Andrew Biggs,
                  title: Study and Work in Australia
                  top_image: https://www.bangkokpost.com/media/content/20170620/c1_1272315_170620160518_620x413.jpg
                  video:
                  - https://www.youtube.com/embed/8I9uQVHluBk
                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true              
components:
  schemas:
    success:
      type: object
      properties:
        content:
          type: object
          example: {<Json Object>}
          description: The result of the API call
          properties:
            all_images: 
              type: array
              items:
                type: string
              example: 
                - https://static.bangkokpost.com/media/content/20170620/2363063.jpg
                - https://www.bangkokpost.com/media/content/20170620/c1_1272315_170620160518_620x413.jpg
                - https://static.bangkokpost.com/media/content/20170620/2364459.jpg
                - https://static.bangkokpost.com/media/content/20170620/2363071.jpg
                - https://static.bangkokpost.com/media/content/20170620/2364455.jpg
                - https://static.bangkokpost.com/media/content/20170620/2363075.jpg
              description: All images of new article.
            authors: 
              type: array
              items:
                type: string
              example: 
                - Bangkok Post Public Company Limited
              description: Authors of new article.
            keywords: 
              type: array
              items:
                type: string
              example: 
                - scholarships
                - opportunities
                - fair
                - study
                - learning
                - worlds
              description: NLP processed keywords from news article.
            language: 
              type: string
              example: "en"
              description: Language of news article.
            link: 
              type: string
              example: "https://www.bangkokpost.com/learning/news/1272315/study-and-work-in-australia-%E2%80%93-many-opportunities-ahead-"
              description: Main article link url.
            publish_date: 
              type: string
              example: 2020-09-30T07:11:15
              description: Published date of news article.
            summary: 
              type: string
              example: "Australia is a country welcoming international students to study at all levels of education with its quality and the part-time work rights given.\nMoreover, there are opportunities to work full-time and to migrate and hold Australian citizenship after graduation from Australia.\nStudy, Work and Live in one of the World's most liveable countries.\n\"Post Study Work Rights and Pathways to Australian Permanent"
              description: Main content of news article.
            text: 
              type: string
              example: "Australia is a country welcoming international students to study at all levels of education with its quality and the part-time work rights given. Moreover, there are opportunities to work full-time and to migrate and hold Australian citizenship after graduation from Australia. Especially, engineers, IT specialists and accountants, and many more, are on the list of occupations which Australia is demanding.\n\nStudy, Work and Live in one of the World's most liveable countries.\n\nDon't miss the chance to interview directly with 40 leading universities and institutions from across Australia. Application fee waivers and scholarships are also available.\n\nUnique! \"Post Study Work Rights and Pathways to Australian Permanent Resident\" seminar by Dr. Visa, Australian Registered Migration Agent, and special talks by Andrew Biggs,"
              description: Full text content of news article.
            title: 
              type: string
              example: "Study and Work in Australia"
              description: Title of news article.
            top_image: 
              type: string
              example: "https://www.bangkokpost.com/media/content/20170620/c1_1272315_170620160518_620x413.jpg"
              description: Published image of news article.
            video: 
              type: array
              items:
                type: string              
              example: 
                  - https://www.youtube.com/embed/8I9uQVHluBk
              description: All video clips related to news article if available.
        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jun 10, 2022
              x-details: Major version release
              description: Latest Version
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Aug 07, 2020
              x-details: Initial version release
              description: Old Version
    input:
      type: object
      required:
        - url       
      properties:
        url:
          type: string
          example: https://www.bangkokpost.com/
          default: true
          description: The absolute input url, i.e exact, full address (URL) to the page.
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
