openapi: 3.0.1
info:
  title: PDF Extractor
  description: |+
    This Utility microservice extracts the text content of the input PDF document  with the option to extract specific pages.
    
    It also extracts from password-protected PDFs, if the correct password is provided.
        
    Output format supported: plain text or HTML.
    
    Supported languages: Hindi, German, Spanish, Portuguese, French, Turkish, Italian, Russian, Arabic, Indonesian, Chinese, Japanese and Korean.
    
    The size of your PDF file should **not exceed 7 MB**.
  x-additionalinfo: |+
    Suggested Use Cases:
    - Used for pre/post processing of documents so that the output can paired with another microservice to address a specific solution. For example, text extracted from the PDF document can be used with a Voice microservice such as Text-to-Speech.

    - Can be used for solutions related to processing workflows that are document-heavy so that the user can focus on the more value-added decisions. Documents in a variety of formats can be taken in to return cleanly structured data. Examples included mortgage processing, procurement data etc.
  version: '1.0.0'
  x-subscribelink: pdf_extractor
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 7MB/Call
  x-inputfilelimit: |+
    Process up to 7 MB of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    File size cannot exceed 7 MB.
  x-apidetailsdesc: |+
    Extracts text content from pdf docs.  
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v1.0.0"
  description: "Published Date - Jul 30, 2020"  
paths:
  /microservices/utility/pdfextractor/v1.0/getresults:
    post:
      tags:
        - v1.0.0
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/success'
                    example:
                      results: "\\n L  328/84 \\n Official  Journal  of  the  European  Union \\n EN \\n
                        18.12.2019 \\n DECISIONS \\n COMMISSION IMPLEMENTING DECISION (EU) 2019/2166 \\n
                        of 16 December 2019 \\n amending Implementing Decision 2014/908/EU as regards the
                        inclusion of Serbia and South Korea in \\n the  lists  of  third  countries  and
                        \ territories  whose  supervisory  and  regulatory  requirements"
                      message: Successfully Processed
                      status: Success
                      extracted_details: "[1, 3] pages are Extracted...."
              '401':
                description: Unauthorized
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/unauthorized'
              '402':
                description: Payment Required
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/paymentrequired'
              '403':
                description: Forbidden
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/forbidden'
              '404':
                description: Not Found
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/notfound'
              '419':
                description: Input Field Missing
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/inputfieldmissing'
              '413':
                description: Payload Too Large
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/inputlimitexceeded'
              '415':
                description: Unsupported Media Type
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/invalidinput'
              '500':
                description: Internal Server Error
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/servererror'
              '504':
                description: Gateway Timeout
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/input'                     
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: string
          example: \n L  328/84 \n Official  Journal  of  the  European  Union \n EN \n 18.12.2019 \n DECISIONS \n COMMISSION IMPLEMENTING DECISION (EU) 2019/2166 \n of 16 December 2019 \n amending Implementing Decision 2014/908/EU as regards the inclusion of Serbia and South Korea in \n the  lists  of  third  countries  and  territories  whose  supervisory  and  regulatory  requirements
          description: The result of the API call.
        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure
        extracted_details:
          type: string
          example: "[1, 3] pages are Extracted...."
          description: Extracted page and file details          
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v2.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 13, 2022
              x-details: Initial version release
              description: Latest Version
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 30, 2020
              x-details: Initial version release
              description: Old Version
    input:
      type: object
      required:
        - filePath
      properties:
        filePath:
          type: string
          format: binary
          default: true
          example: sample.pdf
          description: The file path that describes the location of the file to be converted. Text-only PDF files are supported. Image or mixed PDF files are not recommended.
        pageNumbers:
          type: string
          default: false
          example: "1,3,6"
          description: Page numbers, example 1,3,6. Default all pages
        maxPages:
          type: integer
          format: int32
          default: false
          example: "3"
          description: Maximum number of pages. Default all pages
        startPage:
          type: integer
          format: int32
          default: false
          example: "1"
          description: Starting page number, if used endPage parameter is mandatory
        endPage:
          type: integer
          format: int32
          default: false
          example: "5"
          description: End of page number, if used startPage parameter is mandatory
        convertType:
          type: string
          default: false
          example: "txt"
          description: Convertion type (txt / html). Default type is txt
        passWord:
          type: string
          default: false
          example: "xxxxxxxx"
          description: Password for protected pdf
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
