openapi: 3.0.1
info:
  title: Wikipedia Retrieval
  description: |+
    This Utility microservice provides the user with a Wikipedia article based on the input keyword. Refer to this link for the full list of Wikipedias - <u>https://meta.wikimedia.org/wiki/List_of_Wikipedias</u>
  x-additionalinfo: |+
    Suggested Use Cases:
    - Access topics within Wikipedia with great specificity. Can be used for research/study-related solutions by using information from this microservice to compare articles, revisions and more.

    - Extract the most relevant content from Wikipedia’s categories to provide a text analysis service to ascertain what any text is in reference to.
  version: '1.0.0'
  x-subscribelink: wikipedia_retrieval
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | Single String /Call
  x-inputfilelimit: |+
    Process Single String per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Keyword with a string.
  x-apidetailsdesc: |+
    Provide Wikipedia article based on the input keyword.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v1.0.0"
  description: "Published Date - Jan 11, 2021"
paths:
  /microservices/utility/wikipedia/v1/getresults:
    post:
      tags:
        - v1.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results:
                  content: Singapore officially the Republic of Singapore, is a sovereign city-state
                    and island country located in maritime Southeast Asia.  Singapore lies about one
                    degree of latitude (137 kilometres or 85 miles) north of the equator.
                  images:
                  - https://upload.wikimedia.org/wikipedia/commons/f/f5/0008871_-_Krung_Thep_Bridge_001.jpg
                  - https://upload.wikimedia.org/wikipedia/commons/1/12/2014_Singapore_Products_Export_Treemap.png
                  - https://upload.wikimedia.org/wikipedia/commons/1/1b/2017_G20_Hamburg_summit_leaders_group_photo.jpg
                  - https://upload.wikimedia.org/wikipedia/commons/1/10/A_Night_Perspective_on_the_Singapore_Merlion_%288347645113%29.jpg
                  links:
                  - 65
                  - ".sg"
                  - 126 Squadron, Republic of Singapore Air Force
                  - 13th Parliament of Singapore
                  - 16th Summit of the Non-Aligned Movement
                  - 1915 Singapore Mutiny
                  pageid: 27318
                  summary: Singapore officially the Republic of Singapore, is a sovereign city-state
                    and island country located in maritime Southeast Asia. Singapore lies about one
                    degree of latitude (137 kilometres or 85 miles) north of the equator.
                  thumbnail:
                    height: 333
                    source: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/500px-Flag_of_Singapore.svg.png
                    width: 500
                  url: https://en.wikipedia.org/wiki/Singapore
                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded' 
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json Object of returned results
          properties:
            content:
              type: string
              example: "Singapore officially the Republic of Singapore, is a sovereign city-state and island country located in maritime Southeast Asia. 
                Singapore lies about one degree of latitude (137 kilometres or 85 miles) north of the equator."
              description: Plain text content of the page, excluding images, tables, and other data.
            images:
              type: array
              example: ["https://upload.wikimedia.org/wikipedia/commons/f/f5/0008871_-_Krung_Thep_Bridge_001.jpg","https://upload.wikimedia.org/wikipedia/commons/1/12/2014_Singapore_Products_Export_Treemap.png"]
              description: List of URLs of images on the page.
              items:
                oneOf:
                - type: string
                  format: list
                  example: https://upload.wikimedia.org/wikipedia/commons/f/f5/0008871_-_Krung_Thep_Bridge_001.jpg
                - type: string
                  format: list
                  example: https://upload.wikimedia.org/wikipedia/commons/1/12/2014_Singapore_Products_Export_Treemap.png
                - type: string
                  format: list
                  example: https://upload.wikimedia.org/wikipedia/commons/1/1b/2017_G20_Hamburg_summit_leaders_group_photo.jpg
                - type: string
                  format: list
                  example: https://upload.wikimedia.org/wikipedia/commons/1/10/A_Night_Perspective_on_the_Singapore_Merlion_%288347645113%29.jpg
            links:
              type: array
              example: [".sg","126 Squadron, Republic of Singapore Air Force","13th Parliament of Singapore","16th Summit of the Non-Aligned Movement"]
              description: List of titles of Wikipedia page links on a page.
              items:
                oneOf:
                - type: string
                  format: list
                  example: +65
                - type: string
                  format: list
                  example: .sg
                - type: string
                  format: list
                  example: 126 Squadron, Republic of Singapore Air Force
                - type: string
                  format: list
                  example: 13th Parliament of Singapore
                - type: string
                  format: list
                  example: 16th Summit of the Non-Aligned Movement
                - type: string
                  format: list
                  example: 1915 Singapore Mutiny
            pageid:
              type: integer
              format: int32
              example: 27318
              description: The id of the page requested
            summary:
              type: string
              example: Singapore officially the Republic of Singapore, is a sovereign city-state and island country located in maritime Southeast Asia. 
                  Singapore lies about one degree of latitude (137 kilometres or 85 miles) north of the equator.
              description: A short summary of the Wikipedia article that was requested
            thumbnail:
              type: object
              example: {"height":333,"source":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/500px-Flag_of_Singapore.svg.png", "width":500}
              description: URL and dimensions of thumbnail image associated with page, if any.
              properties:
                height:
                  type: integer
                  format: int32
                  example: 333
                  description: Height of the thumbnail image
                source:
                  type: string
                  example: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/500px-Flag_of_Singapore.svg.png
                  description: Source URL of the thumbnail image
                width:
                  type: integer
                  format: int32
                  example: 500
                  description: Width of the thumbnail image
            url: 
              type: string
              example: https://en.wikipedia.org/wiki/Singapore
              description: The website url of the requested wikipedia articles
        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v2.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jun 08, 2022
              x-details: Major version update
              description: Latest Version
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jan 11, 2021
              x-details: Patch Update, Optimization and thumbnail is added as an additional field 
              description: Latest Version
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Apr 23, 2020
              x-details: Initial version release
              description: Archived
    input:
      type: object
      properties:
        keyword:
          type: string
          example: Singapore
          default: true
          description: The search term, highest match to the title of the Wikipedia page. Not Mandatory when pageid is given.
        pageid: 
          type: integer
          format: int32
          default: false
          example: 27318
          description: The Wikipedia id of the page requested. Mandatory only when title is not given.
        language:
          type: string
          default: false
          example: en
          description: Indicates the language in which the Wikipedia page is written. Default is English, for other languages give the input as ISO 639-1 language code. Please refer this link for language code https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
        additional_fields:
          type: string
          default: false
          example: all
          description: The default returns the pageid, url, summary and thumbnail, when given “all” - returns all the fields i.e pageid, url, summary, content, links, images and thumbnail.
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
