openapi: 3.0.1
info:
  title: Youtube Video Downloader
  description: |+
    This Utility microservice retrieves the Youtube video of the input URL and outputs a download link.
  x-additionalinfo: |+
    Suggested Use Cases:
    - Can be integrated into apps used to download and watch videos when the user wants to save limited data.
  version: '0.2.0'
  x-subscribelink: youtube_video_downloader
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 10MB/Call
  x-inputfilelimit: |+
    Process up to 10000 kb of data or chat per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by the amount of data transferred.
  x-notes: |+
    Payload size cannot exceed 10 MB.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v0.2.0"
  description: "Published Date - Aug 04, 2022"
paths:
  /microservices/utility/downloadyoutubevideos/v0.2/getresults:
    post:
      tags:
        - v0.2.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results:
                  url: https://storage.googleapis.com/youtubedownload/video.mp4?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=cloudstorage%40sentient-231509.iam.gserviceaccount.com%2F20200513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20200513T115310Z&X-Goog-Expires=6000&X-Goog-SignedHeaders=host&X-Goog-Signature=730f588eb4794828389c6a098002d666b307ab695dbd07f84e5309f79503e857e2d8352e11125a0d569f7e3704da6a0320e426f7fe99ed68d965d3812700c4930060e95da1f7d0694c7751ca493c3f097bcd85a37f33ee8a0a7c7366a8aeba2f5bae7814cc1f0ec5f397ebe70f0bc9bcb82be8843db609ebef01953ae3fdd82d48b39184ac566d570cd3a2b3c1f1a09353f0b2d83643eb1b3140850585a299ada899f6473e76c585128d0b864724f67430f6b2b8798e4399c991d97e2716c5382b6597fca8ee43e72f409848491109ba093399355eeb76b92bf769d2e10e5d2952615e8fbc7798bb7bca8d71ef631339634911346d0175cc45fb691d6c8b9cae
                  message: Successfully downloaded and stored in Google Cloud Storage.
                  status: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json Object of returned results
          properties:
            url: 
              type: string
              description: Pre-signed URL to download the video
              example: https://storage.googleapis.com/youtubedownload/video.mp4?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=cloudstorage%40sentient-231509.iam.gserviceaccount.com%2F20200513%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20200513T115310Z&X-Goog-Expires=6000&X-Goog-SignedHeaders=host&X-Goog-Signature=730f588eb4794828389c6a098002d666b307ab695dbd07f84e5309f79503e857e2d8352e11125a0d569f7e3704da6a0320e426f7fe99ed68d965d3812700c4930060e95da1f7d0694c7751ca493c3f097bcd85a37f33ee8a0a7c7366a8aeba2f5bae7814cc1f0ec5f397ebe70f0bc9bcb82be8843db609ebef01953ae3fdd82d48b39184ac566d570cd3a2b3c1f1a09353f0b2d83643eb1b3140850585a299ada899f6473e76c585128d0b864724f67430f6b2b8798e4399c991d97e2716c5382b6597fca8ee43e72f409848491109ba093399355eeb76b92bf769d2e10e5d2952615e8fbc7798bb7bca8d71ef631339634911346d0175cc45fb691d6c8b9cae
        message:
          type: string
          example: Successfully downloaded and stored in Google Cloud Storage.
          description: Detail description on the API status
        status:
          type: string
          example: success
          description: The status of the API call success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure      
    input:
      type: object
      properties:
        url:
          type: string
          default: true
          example: https://www.youtube.com/watch?v=1bumPyvzCyo
          description: |+
            Youtube URL.
    versions:
      type: object
      properties: 
        v0.2.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Aug 04, 2022
              x-details: Initial version release
              description: Latest Version
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
