openapi: 3.0.1
info:
  title: Demographics Classification
  description: |+
    This Computer Vision microservice identifies faces within an input image and predicts the demographics of each face (age, gender and race).</br>
    The image is processed as an input encoded using base64. The results will then be returned back to the user as a JSON output together with bounding box coordinates for each face. Races include: Asian, Indian, White, Black, Middle Eastern and Latino Hispanic</br>
    The size of your image file should **not exceed 10 MB**, and the image dimension should be **at least 416x416 pixels**.
  x-additionalinfo: |+
    Suggested Use Cases:
    - This microservice can be used as a solution to help businesses better understand and connect with their customers, engage new prospects and increase revenue. For example, it can be used to improve visitor experience and optimize operations in retail, leisure, and other sectors by identifying the type of demogrpahic that frequents a certain place the most. It can also be used to create intelligent prospect lists that ensure one is always maximizing their marketing investment.
  version: v0.1.0
  x-subscribelink: demographics_classification
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 10MB/Call
  x-inputfilelimit: |+
    Process up to 10MB of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    File size cannot exceed 10 MB.
  x-apidetailsdesc: |+
    Identifies faces within an input image and predicts the demographics.
servers:
  - url: 'https://apis.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Dec 09, 2020"
paths:
  /microservices/cv/democlass/v0/getpredictions:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results: 
                  persons:
                  - age: 33.21062944528088
                    bbox:
                      bottom: 459
                      left: 82
                      right: 393
                      top: 0
                    gender: Man
                    race: white

                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'  
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true


components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            persons:
              description: Demographic details of the detected person
              example:
                age: 33.21062944528088
                bbox:
                  bottom: 459
                  left: 82
                  right: 393
                  top: 0
                gender: Man
                race: white
              items:
                properties:
                  description: Demographic details of the detected person
                  example: ' '
                  properties:
                    age:
                      description: Age of the detected person in the input image 
                      example: 33.21062944528088
                      type: float
                    bbox:
                      description: Bounding box of the detected person in the input image 
                      example: ' '
                      properties:
                        bottom:
                          description: Bottom coordinate of the box
                          example: 459
                          type: integer
                        left:
                          description: Left coordinate of the box
                          example: 82
                          type: integer
                        right:
                          description: Right coordinate of the box
                          example: 393
                          type: integer
                        top:
                          description: Top coordinate of the box
                          example: 0
                          type: integer
                      type: object
                    gender:
                      description: Gender of the detected person in the input image
                      example: Man
                      type: string
                    race:
                      description: Race of the detected person in the input image
                      example: white
                      type: string
                  type: object
                type: object
              type: array

        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure
        
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Dec 09, 2020
                x-details: Initial version release
                description: Latest Version
    input:
      type: object
      required:
      
        - image_base64
      
      properties:
        image_base64:
          x-name: image_base64
          type: string
          default: True
          example: /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUG...
          description: |+
            Input image file in base64 format.
        
        
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
