openapi: 3.0.1
info:
  title: Invoice Scanner
  description: |+
      This Computer Vision microservice takes in invoices and extracts meaningful and structured data, including the total amount, tax amount, date and merchant name.

      The API will return a JSON containing all data that could be extracted, along with details of where that information was on the page, confidence values, and the coordinates containing the data field in the original document. This API is optimized for computer generated PDFs but also supports pdf scans, png, jpeg, tiff, jfif, and docx files.
  version: '0.1.0'
  x-subscribelink: invoice_scanner
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 10MB/Call
  x-inputfilelimit: |+
    Process up to 10MB of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    File size cannot exceed 10 MB.
  x-apidetailsdesc: |+
    Extracts to meaningful and structured data from Invoice docs.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - Aug 11, 2021"
paths:
  /microservices/cv/scaninvoice/v0/getresults:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: {"message": "Successfully Processed","results":{"scanDocuments":{"data":{"BigBoxes":[{"box":[102,131,227,166,164.5,148.5],"page":0}],"Currency":{"UICategory":"VAT&Amounts","UIName":"Currency","UIType":"Text","matches":[{"keyword":[1160,1594,1171,1616,1165.5,1605,"$","$"],"match":"$","matchmulti":"$","page":0,"value":[1160,1594,1171,1616,1165.5,1605,"$","$"]}]},"Customer":null,"DetectedText":"GSSAINVOICEThankyouc/oGregDerderianTreasurer32TinkerRoadNashuaNH03064Phone603-595-4357faxnoneDATE:INVOICE#FOR:May22009100AnnualDuesBillTo:GSSAMember2009PhoneDESCRIPTIONAMOUNTAnnualDuesperteam2009summerswimseason$100.00TOTAL$100.00MakeallcheckspayabletoGSSAIfyouhaveanyquestionsconcerningthisinvoicecontactNaGregDerderianTreasurerTHANKYOUFORYOURMEMBERSHIP!","DocSize":[[2000,1545]],"Email":{"UICategory":"Vendor&Customer","UIName":"Email","UIType":"Text","matches":[{"keyword":null,"match":null,"matchmulti":null,"page":null,"value":null}]},"GSTNumber":{"UICategory":"Vendor&Customer","UIName":"GSTNumber","UIType":"Text","matches":[{"keyword":null,"match":null,"matchmulti":null,"page":null,"value":null}]},"LineItems":[[{"Amount":[22009],"Description":["32TinkerRoad","DATE:"]}]],"LineItems_standardHeader":[[{"Description":"32TinkerRoadDATE:","LineAmount":22009,"Quantity":1,"UnitAmount":22009}]],"OtherDate":{"UICategory":"BasicInformation","UIName":"OtherDate","UIType":"Date","matches":[{"keyword":null,"match":"2009-05-02","matchmulti":"May22009","page":0,"value":[1232,260]}]},"SenderAddress":{"UICategory":"Vendor&Customer","UIName":"VendorAddress","UIType":"Text","matches":[{"keyword":[102,131,227,166,164.5,148.5,"GSSA\n","GSSA\n"],"match":"c/oGregDerderianTreasurer\n32TinkerRoad\nNashua\nNH03064\nPhone603-595-4357\nfaxnone\n","matchmulti":"c/oGregDerderianTreasurer32TinkerRoadNashuaNH03064Phone603-595-4357Faxnone","page":0,"value":[97,231,457,349,277,290,"c/oGregDerderianTreasurer\n32TinkerRoad\nNashua\nNH03064\nPhone603-595-4357\nfaxnone\n","c/oGregDerderianTreasurer\n32TinkerRoad\nNashua\nNH03064\nPhone603-595-4357\nFaxnone\n"]}]},"ServiceCharge":{"UICategory":"VAT&Amounts","UIName":"ServiceCharge","UIType":"Amount","matches":[{"keyword":null,"match":null,"matchmulti":null,"page":null,"value":null}]},"docId":7905,"status":"COMPLETED"}},"status":"Success"}}     
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/input'
        required: true              
components:
  schemas:
    success:
        type: object
        properties: 
          results:
            type: object
            example: { "<Json": "Object>" }
            description: The result of the API call
            properties:
              scandocuments: 
                type: object
                example: { "<Json": "Object>" }
                description: The details of documents
                properties:
                  docId:
                    type: integer
                    format: int32
                    example: 102581
                    description: Document ID
                  status:
                    type: string
                    example: COMPLETED
                    description: Status of staple API
                  data:
                    type: object
                    example: { "<Json": "Object>" }
                    description: The details scan of document data
                    properties:
                      docsize:
                        type: array
                        example: [[1990,1490]]
                        description: An array contain the size info of template
                        items:
                          oneOf:
                            - type: number
                              example: 1990
                            - type: number
                              example: 1490  
                      num_pages:
                        type: integer
                        format: int32
                        example: 1
                        description: Total Pages
                      customer:
                        type: string
                        example: XYZ Buyer
                        description: Customer Name
                      supplier:
                        type: string
                        example: ABC Supplier
                        description: Supplier Name
                      type:
                        type: string
                        example: invoice
                        description: Type of Document
                      invoicenumber:
                        type: string
                        example: INV-4412
                        description: Invoice Number
                      tabledetected:
                        type: boolean
                        example: True
                        description: True if table detected 
                      total:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Invoice Total Amount     
                      subtotal:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Sub-Total
                      taxtotal:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Tax Total 
                      servicecharge:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Service Charge     
                      currency:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Currency  
                      billingdddress:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Billing Address  
                      email:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Email 
                      url:
                        type: object
                        example: { "<Json": "Object>" }
                        description: URL   
                      ponumber:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Purchase Order Number   
                      accountnumber:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Account Number   
                      accountname:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Account Name   
                      swiftcode:
                        type: object
                        example: { "<Json": "Object>" }
                        description: SwiftCode   
                      iban:
                        type: object
                        example: { "<Json": "Object>" }
                        description: International Bank Account Number   
                      freight:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Freight   
                      shippingaddress:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Shipping Address   
                      companyname:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Company Name   
                      senderaddress:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Sender Address   
                      otheraddress:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Other Address   
                      invoicedate:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Invoice Date   
                      paymentdate:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Payment Date   
                      otherdate:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Other Date   
                      lineitems_standardheader:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Line items standard header                           
          message:
            type: string
            example: Successfully Processed
            description: Description of the API status
          status:
            type: string
            example: Success
            description: The status of the API call - success/failure
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Aug 11, 2021
              x-details: Initial version release
              description: Latest Version
    input:
      type: object
      required:
        - file
      properties:
        file:
          type: string
          format: binary
          default: true
          example:  upload file
          description: The file path that describes the location of the receipt document.
        handwritten:
          type: boolean
          example:  'false'
          description: Specify handwritten true or false. Default is false  
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
