openapi: 3.0.1
info:
  title: HDB Lamp Posts Locations (SG)
  description: |+
   This Data microservice returns the indicative location of lamp posts for all Housing Development Board of Singapore (HDB) Towns, HDB Estates and on HDB Land. The features were identified visually from high definition ortho-rectified aerial imagery and manually digitised. The imagery was obtained from Singapore Land Authority (SLA) (captured in 2014). Objects largely obstructed by trees, structures and / or shadow are likely not captured in this dataset. 
   As this is a dataset download microservice, a successful call will return a pre-signed URL where the entire dataset can be downloaded as a CSV file.
   The HDB POTH programme makes selected public and non-public datasets available to developers and companies to improve their service offerings to benefit the lives of Singapore citizens. Sentient.io is proud to partner with HDB to manage and facilitate the sharing of data for the POTH Programme.
  x-additionalinfo: |+
    Download the complete dataset using a pre-signed URL. It's a two steps process  
  
    **Step 1:**  Get the pre-signed URL 
    
    Replace the correct x-api-key, and API endpoint
    
    > **curl -X GET -H "Content-Type: application/json" -H "x-api-key:XXXXX" <API Endpoint>**
    
    **Step 2:**  Download file 
    
    Using the results.url (i.e) the pre-signed URL to download the dataset
    
    > **curl --request GET "results.url" >> "FILE_NAME"**
    
    **Data schema**
    
        | Name  |  Type |  Size | Description  |
        |---|---|---|---|---|
        |  FEATID | Integer  |  N/A |  Feature ID. Unique running number. |
        |  TYPE |  Char | N/A	  | Captures the type of object.  |
        |  LVL |  Char | N/A	  | Captures whether the object is located at Ground level or Above Ground level.  |
        |  QUALITY |  Char | N/A	  | Captures whether the section of the feature was Fully Visible or Partially Visible.  |
        |  INC_CRC |  Varchar | 50	  | Sub Location Id  |
        |  FMEL_UPD_D |  Datetime | N/A	  | Area of the feature  |
        |  x |  Float | N/A	  | ESRI x coordinate  |
        |  y |  Float | N/A	  | ESRI y coordinate  |
  version: '0.1'
servers:
  - url: 'https://api.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Feb 07, 2020"

paths:
   /DaaS/prod/hdb/amenities/gs/csv/lamppost/hdb:
    get:
      tags:
        - v0.1
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: 
                results:
                  url: "<pre-signed URL>"
                status: Success
                message: Successfully Processed
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
          results:
            type: object
            example: { "<Json": "Object>" }
            description: Json Object of returned results
            properties:
              url: 
                type: string
                description: pre-signed URL to download the file
                example: "<pre-signed URL>"
          status:
            type: string
            example: Success
            description: The status of the API call. success/failure
          message:
            type: string
            example: Successfully Processed
            description: Detail description on the api status
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Feb 07, 2020
              description: Initial version release
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
